ifdef CONFIG_EMBEDDED_CERTIFICATES
ifdef CONFIG_CA_CERTIFICATE
COMPONENT_EMBED_TXTFILES += certs/CA.crt
endif
ifdef CONFIG_CLIENT_CERTIFICATES
COMPONENT_EMBED_TXTFILES += certs/esp32.crt certs/esp32.key
endif
endif

COMPONENT_ADD_INCLUDEDIRS := include src .
COMPONENT_SRCDIRS += src

VERSION=0.0.1-1
CXXFLAGS += -DVERSION="\"$(VERSION)\""
